from typing import Protocol

from app.models.report import AnalysisJob, Report


class ReportRepository(Protocol):
    async def submit(self, job: AnalysisJob, cache_key: str) -> tuple[AnalysisJob, bool]: ...
    async def get_job(self, job_id: str) -> AnalysisJob | None: ...
    async def update_job(self, job: AnalysisJob) -> None: ...
    async def save_report(self, report: Report) -> None: ...
    async def get_report(self, report_id: str) -> Report | None: ...
    async def reserve_budget(self, key: str, limit: int) -> bool: ...
    async def recover_interrupted(self) -> None: ...
